namespace: romlecat
name: osc
version: 0.0.3
readme: README.md
authors:
- Romain Lecat
description: Dynamic inventory for Outscale FCU VMs.
license:
- MIT
tags: []
dependencies: {}
repository: https://github.com/romlecat/ansible-osc
documentation: https://github.com/romlecat/ansible-osc
homepage: https://github.com/romlecat/ansible-osc
issues: https://github.com/romlecat/ansible-osc/issues
